SELECT 1;
INSERT INTO T_USER (USR_USERNAME,USR_FIRST_NAME, USR_LAST_NAME, USR_IS_ACTIVE, USR_EMAIL,IS_ENABLED,PWD_RESET_DATE,USR_PASS_HASH,USR_IMG_URL,USR_ROLE,CREATED_BY, VERSION) VALUES 
('s.bendrioue','Said', 'BENDRIOUE', 1, 's.bendrioue@gmail.com',1,'2010-10-01','$2a$08$UkVvwpULis18S19S5pZFn.MAMkQPsdG9ww2r0dVxP/x.HMLtYYq5.','s.bendrioue.jpg','RH','S.BENDRIOUE', 0);

INSERT INTO T_USER (USR_USERNAME,USR_FIRST_NAME, USR_LAST_NAME, USR_IS_ACTIVE, USR_EMAIL,IS_ENABLED,PWD_RESET_DATE,USR_PASS_HASH,USR_IMG_URL,USR_ROLE,CREATED_BY, VERSION) VALUES 
('a.doumi','Anas', 'DOUMI', 1, 'ad.anasdoumi@gmail.com',1,'2010-10-01','$2a$08$UkVvwpULis18S19S5pZFn.MAMkQPsdG9ww2r0dVxP/x.HMLtYYq5.','anasdoumi.jpg','COL','S.BENDRIOUE', 0);

INSERT INTO T_USER (USR_USERNAME,USR_FIRST_NAME, USR_LAST_NAME, USR_IS_ACTIVE, USR_EMAIL,IS_ENABLED,PWD_RESET_DATE,USR_PASS_HASH,USR_IMG_URL,USR_ROLE,CREATED_BY, VERSION) VALUES 
('r.maich','Reda', 'MAICH', 1, 'r.maich@gmail.com',1,'2010-10-01','$2a$08$UkVvwpULis18S19S5pZFn.MAMkQPsdG9ww2r0dVxP/x.HMLtYYq5.','r.maich.jpg','MNGR','S.BENDRIOUE', 0);